sample:
  initialize: true
  firstNames:
    - Robert
    - DaShaun
  lastNames:
    - Sirchia
    - Carter
  emails:
    - robertsi@magenic.com
    - dacarter@pivotal.io

security:
  basic:
    enabled: false

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update