sample:
  initialize: true
  firstNames:
    - Sean
    - DaShaun
  lastNames:
    - Noyes
    - Carter
  emails:
    - snoyes@pivotal.io
    - dacarter@pivotal.io

security:
  basic:
    enabled: false

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
